---
output:
  html_document:
    df_print: paged
    includes:
      in_header: header.html
      before_body: hVastatrix.html
      after_body: citate.html
    css: styles.css
---
```{r, include=FALSE}
  library(ggplot2)
  library(dplyr)
  library(readxl)
  library(viridisLite)
  library(plotly)
```

```{r, include=FALSE}
  data <- read_excel("Base_de_datos/DataBase_Markers_CENHV.xlsx")
  rhg_cols <- c( "#370617", "#6A040F", "#771C19", "#AA3929", "#E25033", "#F27314", "#F8A31B",
               "#E2C59F", "#B6C5CC", "#8E9CA3", "#556670", "#000000", "#03071E")
```

```{r, include=FALSE}
  #Tabla de frecuencias por tipo
  type <- ftable(data$SSR_type)
  typeData <- as.data.frame(type)
  names(typeData)[1] = "Tipo"
  names(typeData)[2] = "Frecuencia"
  typeData = arrange(typeData, desc(Frecuencia))
  
  #secuencias frecuentes
  seque <- ftable(data$SSR_summary_sequence)
  sequeData <- as.data.frame(seque)
  sequeData = arrange(sequeData, desc(Freq))
  sequeMain <- top_n( sequeData, 10, Freq)
```

:::: {style="display: flex;"}

::: {}

```{r, class.source="watch-out", echo=FALSE}
  Microsatellites<-"Microsatellites"
  Microsatellites
```

```{r, class.source="watch-out", echo=FALSE}
  GcoveredMB <- "Genome covered MB"
  GcoveredMB
```

```{r, class.source="watch-out", echo=FALSE}
  GcoveredPer <- "Genome covered"
  GcoveredPer
```

```{r, class.source="watch-out", echo=FALSE}
  SSRperMB <- "SSR MB"
  SSRperMB
```

:::

::: {}

```{r, echo=FALSE, warning=FALSE, fig.height = 4, fig.align ='center'}
  # Pie plot
  m <- list(
  l = 50,
  r = 50,
  b = 100,
  t = 100,
  pad = 4
  )  

  pie <- plot_ly(typeData, labels = ~Tipo, values = ~Frecuencia,
                 textposition = 'inside',
                 textinfo = 'percent',
                 insidetextfont = list(color = '#FFFFFF'),
                 hoverinfo = 'text',
                 text = ~paste(Tipo, ':', Frecuencia),
                 marker = list(colors = rhg_cols,
                      line = list(color = '#FFFFFF', width = 1)),
                 showlegend = TRUE,
                 insidetextorientation='radial')
  pie <- pie %>% add_pie(hole = 0.6)
  pie <- pie %>% layout(title = 'Motiv Size Distribution',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  pie <- pie %>% layout(autosize = F, width = 400, margin = m)
  pie
```

:::

::: {}

```{r, echo=FALSE, warning=FALSE, fig.width = 6, fig.height = 4, fig.align ='center'}
#Barplot
  n <- list(
  l = 50,
  r = 50,
  b = 100,
  t = 100,
  pad = 4
  )  

sequeMain$Var1 = with(sequeMain, reorder(Var1, -Freq, .fun='length'))

barras <- plot_ly(
    x = sequeMain$Var1,
    y = sequeMain$Freq,
    type = 'bar',
    marker = list(color = rhg_cols),
  )
barras <- barras %>% layout(
    title = 'Most Frequent Repeats',
    xaxis = list(
      type = 'category',
      title = 'Sequences',
      tickangle = -45
    ),
    yaxis = list(
      title = 'Frequency',
      range = c(0,16)
    )
  )
barras <- barras %>% layout(autosize = F, width = 500, height = 400, margin = n)
barras
```

:::

::::